# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='longitutde',
            new_name='longitude',
        ),
    ]
